CREATE TABLE dishes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255),
    image_url VARCHAR(255),
    available BOOLEAN,
    tags VARCHAR(255),
    recipe_steps TEXT,
    updated_at TIMESTAMP
);
CREATE TABLE dish_ingredients (
    dish_id BIGINT NOT NULL REFERENCES dishes(id),
    ingredient_name VARCHAR(255)
);
