CREATE TABLE ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(80) NOT NULL,
    normalized_name VARCHAR(80) NOT NULL,
    quantity NUMERIC(12,3) NOT NULL CHECK (quantity >= 0),
    unit VARCHAR(8) NOT NULL CHECK (unit IN ('g', 'kg', 'ml', 'l', '个')),
    location VARCHAR(40) NOT NULL,
    category VARCHAR(20) NOT NULL CHECK (category IN ('蔬菜', '肉禽', '水产', '蛋奶', '主食', '调味', '其他')),
    expires_on DATE,
    expiry_key VARCHAR(10) NOT NULL,
    CONSTRAINT uq_ingredient_batch UNIQUE (normalized_name, unit, location, expiry_key)
);
CREATE INDEX ix_ingredients_expires_on ON ingredients(expires_on);
