spring.application.name=couple-chef
spring.web.resources.static-locations=classpath:/static/
server.address=${SERVER_ADDRESS:127.0.0.1}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/couplechef}
spring.datasource.username=${DB_USER:couplechef}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

